### ISSUE TITLE
Timeout expired 

### ISSUE THREAD

**Issue by rcappe** [persuader72/silla-prism-integration#1]
During the configuration I have received this error message
![image](https://github.com/user-attachments/assets/1072b5ce-15d1-40e4-9a0c-64f929f3af10)
These are the settings on Silla
![image](https://github.com/user-attachments/assets/1f755d6b-6366-4dce-a0c0-8bd63d09ecbf)
I have installed the Silla Prism Solar wallbox integration version v0.4.0

How can I solve or investigate further?

**Comment by persuader72** [comment]
Yes indeed the reported error is quite cryptic  ;)

To check the prism presence i try to subscribe the topic  "0/info/temperature/core" this error states that this topic has not ben received within the allowed period of time. In this case the device is considered not present and the config procedure is interrupted.

Can you send me the output of the topics  related to the prism of your mqtt borker? 

For instance  in my RaspberryPI i can obtain it with this command: 

`mosquitto_sub -v -h 127.0.0.1 -t "prism/#" -u ***** -P *****` 

I let it run at least the time need to acquire a full round of topics. (1 minute is enough)

**Comment by rcappe** [comment]
I'm not sure how to run hemostat_sub command, if you give me some guide I'll try.

In the meantime, I can share the result of the MQTT Explorer
![image](https://github.com/user-attachments/assets/b0c53334-867f-4d31-9820-ec2973a1ba1d)

There are 2 main topic "home" and "prism".
"home" is the old Silla configuration.

**Comment by rcappe** [comment]
I found how to run the command, the information are the same

![image](https://github.com/user-attachments/assets/66d52a69-50e3-4af8-8985-5d06ea902e6c)

**Comment by rcappe** [comment]
I found the problem, my network is divided into a primary network and a dedicated network for IoT devices. 
I tried to connect my PC to the IoT network and ran the configuration wizard. 
It finally worked.
thanks for the support

**Comment by persuader72** [comment]
Good to hear that. :ok_hand:

**Comment by lorenzoprivato** [comment]
> I found the problem, my network is divided into a primary network and a dedicated network for IoT devices. I tried to connect my PC to the IoT network and ran the configuration wizard. It finally worked. thanks for the support


Hi, does "network for IoT devices" mean the silla prism own wifi network?
Unfortunately I have the same timeout problem during the configuration.
I checked twice all, but that's it.
