### ISSUE TITLE
Unable to add a second Prism

### ISSUE THREAD

**Issue by wergio** [persuader72/silla-prism-integration#5]
I've got 2 prism solar

I installed the first, and renamed from "silla_prism" to "silla_prism_pt"

then added the second but it's not working

in the log I've many errors similar to the following for every sensor of the second prism

ERROR (MainThread) [homeassistant.components.binary_sensor] Platform silla_prism does not generate unique IDs. ID prism_online_001 is already used by binary_sensor.silla_prism_pt_online - ignoring binary_sensor.silla_prism_online

I used two different base topics for the two prism:
/home/prismpt/
/home/prismp1/

**Comment by persuader72** [comment]
ok, I think I have undestood the problem, i will try to fix it in the next days.

**Comment by persuader72** [comment]
Try update to 0.5.0,

When you add a new device there is now an optional field named **serial**.
You have to use this field with a different alphanumeric code  for each Prism you have (for example use lettere A for first Prism letter B for second and so on). Don't use spaces or special characters .
The people that have a single prism can leave it blank.

**Comment by wergio** [comment]
now working perfectly! thanks!

a little suggestion: the naming convention you used create entity like binary_sensor.silla_prism_binary_sensor_a02812 (where a02812 is mi serial number)
but the device is named differently so when i try to rename the device it does not rename automatically the entities, see message below
![prismrename](https://github.com/user-attachments/assets/f82fc933-f078-49ca-9ecb-a8e9b54d0a60)
so i must rename manually

i think you can use the same naming convention and it will rename automatically

**Comment by persuader72** [comment]
Ok thanks for the suggestion, I will look into it
